### ISSUE TITLE
Some russian translations for validations messages are incorrect

### ISSUE THREAD

**Issue by alexlvcom** [rollerworks/PasswordStrengthValidator#16]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

There is one duplicate line, and one typo which needs to be fixed:

`<trans-unit id="2">`
`      <source>Your password must include at least one letter.</source>`
`       <target>Пароль должен содержать, по крайней мере, один специальный символ.</target>`
` </trans-unit>`

` <trans-unit id="16">`
`   <source>rollerworks_password.tip.special_chars</source>`
`   <target>добавить специальнгые символы</target>`
` </trans-unit>`

**Comment by sstok** [comment]
No need to open an issue first if you are able to open a pull-request 👍 Thank you for the pull-request.
