### ISSUE TITLE
Allow configuring a threshold for the pwned passwords constraint

### ISSUE THREAD

**Issue by stof** [rollerworks/PasswordStrengthValidator#22]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Currently, the constraint will reject any password found at least once on pwnedpasswords.com. While this is indeed the safest behavior (and so a sensible default), it means blocking half a billion passwords currently.
The blog post announcing the launch of the v2 (which is used here) recognizes this usability nightmare, and explains that this is the reason why a count is provided for each password: https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/#eachpasswordnowhasacountnexttoit

I would be great to allow configuring the threshold at which passwords should be blocked (the existing behavior corresponds to `threshold=1`)

**Comment by robbah** [comment]
I would like to use this feature as well. How can i use the treshold for symfony 3.4?

**Comment by stof** [comment]
this feature is not implemented in this bundle. So it cannot be used. This issue is a feature request.

**Comment by stof** [comment]
This feature is supported by the NotCompromisedPassword constraint available in Symfony 4.2+.

And given there is this core constraint available, I doubt the constraint in this repo will be improved further.
