### ISSUE TITLE
blacklisting password for MySQL

### ISSUE THREAD

**Issue by ickbinhier** [rollerworks/PasswordStrengthValidator#25]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? |no
| RFC?             | yes

Is it possible that the MySQL (PDO) functionality for the "blacklisting password" is integrated into the code?

My SQLite database is now quite large and it will be difficult to keep this between the hosts up to date. The central MySQL server would be more practical at this point.

**Comment by sstok** [comment]
For MySQL you can use the https://github.com/rollerworks/PasswordStrengthValidator/blob/master/src/Blacklist/PdoProvider.php (Should also work with Doctrine DBAL) 👍 

For Doctrine ORM feel free to open a pull-request (easiest is to use Annotation driver as you don't have configure the mappings).
