### ISSUE TITLE
Translations not working when translation domain for validators is changed

### ISSUE THREAD

**Issue by zoomtronic** [rollerworks/PasswordStrengthValidator#44]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

Hi,

The translations stopped working when a new default domain is set to the validators in the framework.yaml
`validation: { translation_domain: messages }`

Do you know how to fix this ?

I tried to add 
`missingNumbersMessage: "Le mot de passe doit contenir au moins un chiffre.`
in my messages+intl-icu.fr.yaml but its not working too..

**Comment by sstok** [comment]
The `missingNumbersMessage` doesn't exist within the provided translations (it's actually a config key for a custom message of `PasswordRequirements`).

For the `PasswordStrengthValidator` the tips are hard-coded to `validators` domain, if you need to able to change this, please provide a pull request to add an optional argument to validator (to allow changing this value).
