### ISSUE TITLE
Wrong translation for pt-BR special chars requirement

### ISSUE THREAD

**Issue by wguilen** [rollerworks/PasswordStrengthValidator#45]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The brazilian portuguese translation of special chars requirement is wrong, as shown in the image below.
As I'm from Brazil, I'd suggest translating it to: "A senha deve conter pelo menos um caractere especial.".

![Wrong translation of unit 5 for pt_BR](https://user-images.githubusercontent.com/29200516/120815910-a73aa680-c526-11eb-91cc-df71284b239f.png)

**Comment by sstok** [comment]
Can you open a pull request?

**Comment by wguilen** [comment]
Hello, @sstok.

Sorry for the delay. Busy days around here...

I just issued the pull request. Besides what was discussed above, I also improved the translation and fixed the units 15 and 16, which were inverted.
