### ISSUE TITLE
The options "minStrength" must be set for constraint

### ISSUE THREAD

**Issue by RootProgger** [rollerworks/PasswordStrengthValidator#60]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony        | 5.4.0-Beta1
| PHP              | 8.0
| Validator       | latest

I use the Validator per PHP8 Attributes:
```php
#[RollerworksPassword\PasswordStrength(minLength: 6, minStrength: 3)]
private string $plainPassword;
```

When i open the register-form, following exception occurs:

```
The options "minStrength" must be set for constraint "Rollerworks\Component\PasswordStrength\Validator\Constraints\PasswordStrength".
```

PHPStorm says:
`Named arguments order does not match parameters order`
When i change the Param order the same error is shown.

**Comment by sstok** [comment]
This happens because the options are resolved before the arguments are set, and even then the options should still be passed to resolver method.

Technically instead of setting the properties directly, the options (provided as named arguments) should merged the options argument and then passed to the resolve method.

**Comment by RootProgger** [comment]
okey, with:
```
#[RollerworksPassword\PasswordStrength(options: ['minStrength' => 5, 'minLength' => 8])]
```
it works.
But anymwa, this is still a bug?

**Comment by sstok** [comment]
Yes. It should be possible to use the named arguments.

I will try to work on this tomorrow.

**Comment by sstok** [comment]
Should be fixed now. Please try the latest patch release.
