### ISSUE TITLE
Translations are not loaded

### ISSUE THREAD

**Issue by LanmanGroup** [rollerworks/PasswordStrengthValidator#62]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Translations are not loaded. I have to manually copy the file. Is the problem related to the missing DependencyInjection folder?

**Comment by sstok** [comment]
If you are using the library in a Symfony application, you should install the PasswordStrengthValidatorBundle which is will ensure translations are working as expected.
